### ISSUE TITLE
Error occurred while running Task 'run MATLAB command(2)' of type com.mathworks.ci.matlab-bamboo-plugin:runMATLABCommand.

### ISSUE THREAD

**Issue by yitingw3** [mathworks/matlab-bamboo-plugin#31]
I started a Bamboo server on a windows machine, got this error when ran a build plan with run MATLAB cmd.

Reproduce steps:
Start the bamboo server from command prompt as the administrator. Create a plan and link it to [ matlab-bamboo-plugin-bash-repo](https://github.com/yitingw3/matlab-bamboo-plugin-bash-repo), add task using Run MATLAB command or run MATLAB test. 

java.lang.NullPointerException: Log entry can't be null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:226)
	at com.atlassian.bamboo.build.SimpleLogEntry.<init>(SimpleLogEntry.java:33)
	at com.atlassian.bamboo.build.SimpleLogEntry.<init>(SimpleLogEntry.java:28)
	at com.atlassian.bamboo.build.ErrorLogEntry.<init>(ErrorLogEntry.java:11)
	at com.atlassian.bamboo.build.logger.AbstractBuildLogger.addErrorLogEntry(AbstractBuildLogger.java:143)
	at com.mathworks.ci.task.MatlabCommandTask.execute(MatlabCommandTask.java:56)
	at com.atlassian.bamboo.task.TaskExecutorImpl.lambda$executeTasks$2(TaskExecutorImpl.java:317)
	at com.atlassian.bamboo.task.TaskExecutorImpl.executeTaskWithPrePostActions(TaskExecutorImpl.java:252)
	at com.atlassian.bamboo.task.TaskExecutorImpl.executeTasks(TaskExecutorImpl.java:317)
	at com.atlassian.bamboo.task.TaskExecutorImpl.execute(TaskExecutorImpl.java:112)
	at com.atlassian.bamboo.build.pipeline.tasks.ExecuteBuildTask.call(ExecuteBuildTask.java:73)
	at com.atlassian.bamboo.v2.build.agent.DefaultBuildAgent.executeBuildPhase(DefaultBuildAgent.java:203)
	at com.atlassian.bamboo.v2.build.agent.DefaultBuildAgent.build(DefaultBuildAgent.java:175)
	at com.atlassian.bamboo.v2.build.agent.BuildAgentControllerImpl.lambda$waitAndPerformBuild$0(BuildAgentControllerImpl.java:131)
	at com.atlassian.bamboo.variable.CustomVariableContextImpl.withVariableSubstitutor(CustomVariableContextImpl.java:185)
	at com.atlassian.bamboo.v2.build.agent.BuildAgentControllerImpl.waitAndPerformBuild(BuildAgentControllerImpl.java:125)
	at com.atlassian.bamboo.v2.build.agent.DefaultBuildAgent$1.run(DefaultBuildAgent.java:126)
	at com.atlassian.bamboo.utils.BambooRunnables$1.run(BambooRunnables.java:48)
	at com.atlassian.bamboo.security.ImpersonationHelper.runWith(ImpersonationHelper.java:26)
	at com.atlassian.bamboo.security.ImpersonationHelper.runWithSystemAuthority(ImpersonationHelper.java:17)
	at com.atlassian.bamboo.security.ImpersonationHelper$1.run(ImpersonationHelper.java:41)
	at java.lang.Thread.run(Thread.java:750)

**Comment by davidbuzinski** [comment]
It looks like this might be the root cause: https://jira.atlassian.com/browse/BAM-17146

Looking into workarounds
